i4Ds/STIXCore

setup.cfg, stixcore/calibration/tests/test_transmission.py, stixcore/calibration/transmission.py
I'm not sure what to do with this it not great, I have some ideas to improve it as but it does what we need right now, might wait until a need arise.
- The material and components are fixed in the code should probably be read the configuration database to allow different versions
- The detector are all treated the same the fine grid cover is a bit add-hoc could move to per detector approach
- Hard to really test without using the output values form the code itself ...
=> Add calculation of the absortion of X-ray by non-imaging components

stixcore/ephemeris/manager.py, stixcore/ephemeris/tests/test_manager.py, stixcore/ephemeris/tests/test_position.py, stixcore/ephemeris/tests/test_time.py
Create a temporary copy and update the path variable to match the location of the kernels close #11
=> Feat make spice kernel from SOC location indpendent

docs/code_ref/index.rst, docs/code_ref/processing.rst, stixcore/processing/__init__.py, stixcore/processing/decompression.py, stixcore/tmtc/packets.py, stixcore/tmtc/parser.py, stixcore/tmtc/tests/test_packet_factory.py, stixcore/tmtc/tests/test_parser.py, stixcore/tmtc/tm/tm_21.py
=> add decompression to packet processing

stixcore/data/idb/idbVersionHistory.json, stixcore/datetime/datetime.py, stixcore/idb/manager.py, stixcore/idb/tests/data/idbVersionHistory.json, stixcore/idb/tests/test_manager.py, stixcore/processing/levelb.py, stixcore/tmtc/packets.py
will bring a performance improvement by factor 8
=> LevelB without SPICE based on OBT

docs/code_ref/processing.rst, stixcore/idb/idb.py, stixcore/idb/tests/test_idb.py, stixcore/processing/engineering.py
some minor additions that should have come together with the last PR
=> documentation for engineering

stixcore/calibration/tests/test_transmission.py, stixcore/calibration/transmission.py
* Evalute tranmssion at energies not centers
* Add energies to the returned tables
* Update tests for theses changes
* Add function to write transmission tables to csv
=> Update transmission generation code

stixcore/data/test/tmtc/tm/21_6_41_complete.hex, stixcore/processing/LBtoL0.py, stixcore/products/common.py, stixcore/products/level0/quicklook.py, stixcore/products/level1/quicklook.py, stixcore/products/product.py, stixcore/products/tests/test_quicklook.py
* Background
* Spectra
* Variance
* FlareFlag
* EnergyCalibration
* TMStatus (draft)
=> Add rest of ql products to level0

stixcore/products/__init__.py, stixcore/products/level0/housekeeping.py, stixcore/products/level0/quicklook.py, stixcore/products/levelb/binary.py, stixcore/products/tests/test_housekeeping.py
* Mini report TM(3, 25), SSID 1
* Maxi report TM(3, 25), SSID 2
=> Add L0 housekeeping products

stixcore/products/level0/science.py, stixcore/products/tests/test_bsd.py
* Removed factor of 0.5
* Added samples to control info to allow easier debugging/reconstruction
=> Fix bug in aspect time calulation.

stixcore/products/level0/science.py
When doing a final review on the aspect fits files I realised there was a small error in the calculation of the durations.
=> Fix small bug generating incorrect aspect duration.

setup.cfg, stixcore/config/config.py, stixcore/processing/L0toL1.py, stixcore/processing/LBtoL0.py, stixcore/processing/TMTCtoLB.py, stixcore/processing/pipeline.py, stixcore/products/common.py
* Added code to watch a directory for new TM filess
* These tm files are then processed from TM to LB, L0 and L1
* Moved some config into a `stixconfig.ini` file and reader
=> Create code to run in a pipeline operation

stixcore/io/fits/processors.py, stixcore/io/fits/tests/test_processors.py, stixcore/processing/LBtoL0.py, stixcore/processing/TMTCtoLB.py, stixcore/products/level0/science.py, stixcore/products/product.py
* Create fits files based on the parameter names
* For L1 put in human readable subfolders, e.g. events, diagnostics, tm-verify ...
=> Add a L0 and L1 fits for other TM (not BSD or QL or HK) using a DefaultProduct

stixcore/config/config.py, stixcore/data/stixcore.ini, stixcore/io/fits/processors.py, stixcore/processing/L0toL1.py, stixcore/processing/LBtoL0.py, stixcore/processing/TMTCtoLB.py, stixcore/processing/engineering.py, stixcore/products/common.py, stixcore/products/level0/housekeeping.py, stixcore/products/level0/quicklook.py, stixcore/products/level0/science.py, stixcore/products/level1/quicklook.py, stixcore/products/level1/science.py, stixcore/products/product.py, stixcore/time/datetime.py, stixcore/tmtc/packets.py
* Fix the issue with empty packet e.g `NIX00089=0`
* Not all data products have energy info so make optional
* Fix level info not proposing for DefaultProduct
=> Bugfix pipeline testing issues

stixcore/ephemeris/manager.py, stixcore/ephemeris/tests/test_position.py, stixcore/io/fits/processors.py, stixcore/io/fits/tests/test_processors.py, stixcore/time/datetime.py
=> Add code to create spice ephemeris header tuples

docs/Makefile
Add a target that remove generated folders addresses  #13 not done in make as it can be really slow.
=> Feat doc clean

stixcore/data/test/idb/idbVersionHistory.json, stixcore/idb/idb.py, stixcore/idb/tests/test_manager.py, stixcore/products/level0/science.py, stixcore/tmtc/packets.py, stixcore/tmtc/tests/test_packet_factory.py, stixcore/tmtc/tm/tm_21.py
Fix #125 
Fix type of the rcr colum in fits files (was showing up as bool)
=> Fix FSW tigger compression in xray l1 BSD

stixcore/data/test/products/solo_L1_stix-ql-lightcurve_20210116_V01.fits, stixcore/data/test/products/solo_L1_stix-ql-lightcurve_20210117_V01.fits, stixcore/io/fits/processors.py, stixcore/processing/L0toL1.py, stixcore/products/level0/scienceL0.py, stixcore/products/product.py
Closes #174 by implement a custom QTable reader until/if upstream fix happens.
=> Bugfix fits l1 dtypes

stixcore/products/level0/scienceL0.py
=> Fix #115 update detector mask for affect times

stixcore/processing/LBtoL0.py, stixcore/products/level0/quicklookL0.py
=> Fix bug in calibration spectra processing LB to L0

docs/idb_versioning.rst, stixcore/data/idb/idbVersionHistory.json, stixcore/idb/manager.py, stixcore/io/fits/processors.py
* Fix idb folder structure issue
* Update idb version history with real dates
* Fix tiny when round time for fits file in L1 serialisation
=> Follow up to IDB36 update

stixcore/products/level0/quicklookL0.py
(cherry picked from commit f12238de507841d858c5d492a2c417c967180229)
=> Fix bug in QL Background extraction

stixcore/processing/pipeline.py, stixcore/soop/manager.py
add the level2 to the pipeline
spice kernel gets updated (id necessary) before each new TM file is processed
=> extend pipelone to l2 and automatic spice update

stixcore/products/level0/quicklookL0.py
=> Fix bug in calibration spectra now handle differing sub spectra

stixcore/io/fits/processors.py
So at the moment the file mid point is use to determine where it is stored this PR change this to use the start date.
=> Save fits files in folder for the day they start not mid point. 

docs/pipelineconfiguration.rst, setup.cfg, stixcore/data/stixcore.ini, stixcore/io/fits/processors.py, stixcore/processing/pipeline.py, stixcore/processing/pipeline_cli.py, stixcore/processing/pipeline_status.py, stixcore/processing/stix-pipeline, stixcore/processing/tests/test_processing.py, stixcore/products/level2/housekeepingL2.py, stixcore/util/scripts/daily_comparison.py, stixcore/util/scripts/end2end_testing.py, stixcore/util/scripts/stix-pipeline.service
better doc
pipeline as systemd 
pipeline cli with input files
logging
aux product rename
add a status server/client to the pipeline (readonly)
=> pipeline fixes and doc

stixcore/products/level0/scienceL0.py
Fix bug introduced by fix for #253
=> Fix bug introduced in summed pixel data due to varible pixel masks

stixcore/products/level0/scienceL0.py
When investigating #291 it was clear for some specific requests the files are 31 time larger than they need to be (when only the BKG detector) is requested. Further as many of our pixel data request are for large pixels only the are 1/3 larger than necessary. 
This PR subscrits the count array in the detector, pixel and engery dimensions so the files are as small as possible.
**This change would require updates to the python and IDL analysis software**
=> Feat save only requested detector and pixels to fits

stixcore/products/level0/quicklookL0.py
This  PR fixes a  small issue with the formatting of the the QL detector spectra and improves some other aspects of the data product.
=> Improve formatting of the the QL spectra

stixcore/products/level0/scienceL0.py
=> SKM Compression errors in Spectrogram FITS are actually variance values

stixcore/io/fits/processors.py, stixcore/products/level0/quicklookL0.py, stixcore/products/level0/scienceL0.py, stixcore/products/product.py
=> rename "*_err" to "*_comp_err"

stixcore/config/reader.py, stixcore/config/tests/test_reader.py, stixcore/io/fits/processors.py, stixcore/products/common.py, stixcore/products/level0/scienceL0.py, stixcore/products/product.py
- Add code to parse science energy index file into interval tree
- Add code to lookup by date and parse science energy channel definitions
- Small refactor of the code for transforming lb to l0 for BSD spectrogram (left over todo) and was changing the same area
=> Add support for different science energy channels configurations

stixcore/products/level0/scienceL0.py
* No longer rebin onboard summed data to standard science channels
* Fix count array energy dim not being truncated when onboard summing was used
* Rplace energy_bin_mask with energy_bin_edge_mask as the former is degenerate when onboard summing is used
* Update engery tables in fits to represnt channels in the data as requested
=> Fix and update various issues with BSD processing

stixcore/products/level0/scienceL0.py
Missed also slice the count error back down if DSumFix is applied, closes #330
=> Fix count error dims with DSumMask fix

stixcore/data/test.py, stixcore/data/test/products/solo_LB_stix-21-6-24_0000000000-9999999999_V02_2402021788-59493.fits, stixcore/data/test/publish/rid_lut.csv, stixcore/data/test/publish/update_rid_lut.csv, stixcore/processing/tests/test_processing.py, stixcore/products/level0/scienceL0.py
Add new keyword `DATAWARN` if `0` ok if `1` check comments.
Add new comment indicating the trigger values maybe incorrect
Add test
=> Add warning if trigger scaling changes in request

.zenodo.json
Need to update to include other people who haven't directly contributed to code but have contributed.
=> Add Zenodo file
